### PR TITLE
added option to plot to a png file

### PR DESCRIPTION
**Pull request by acaird**
mostly I wanted to play more with matplotlib, and see how close I could get to whatever you used.

also, my emacs config fixed some extraneous EOL spaces, sorry.

### CODE REVIEW

**Comment by acaird** [comment]
added the option of making a pie chart to who_wins.py

**Comment by acaird** [comment]
added xkcd options to both scripts; the --xkcd/-x option makes the plots in the format of an xkcd.com plot

**Comment by acaird** [comment]
Updated README.md file.

**Comment by acaird** [comment]
changed colormap; doesn't match FB pie chart, but is more pretty, IMO.  Also, added a comment about how to set the colormap for matplotlib plots.

**Comment by disser** [comment]
Nice!  I used Google Sheets for the charts on FB, but I like this better.

**Comment by acaird** [comment]
Thanks. :)

It was fun.  Obviously.  Or I wouldn't have done it.

**Pull request merged**
